fix: Feature/update cutadapt wrapper (#67)
I encountered an error in this trimming rule due to 

```
  File "~/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 22, in <module>
    from snakemake.target_jobs import parse_target_jobs_cli_args
  File "~/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/target_jobs.py", line 4, in <module>
    from snakemake.common import parse_key_value_arg
  File "~/mambaforge/envs/snakemake/lib/python3.10/site-packages/snakemake/common/__init__.py", line 284, in <module>
    @contextlib.asynccontextmanager
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
```

Tried running under Python 3.10 and 3.7, still encountered the same
issue, but eventually tracked the rabbit hole down to this.

Updating the wrapper for cutadapt slightly changes the syntax, but no
modification to the config.yaml file is needed. Additionally,
(optionally) I added multithreading, as cutadapt scales quite well.

---------

Co-authored-by: David Laehnemann <david.laehnemann@hhu.de>